import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { AuthService } from '@app/core/services/auth.service';

interface User {
  userId?: string;
  userName: string;
  userEmail: string;
  password: string;
  userMobileNum: string;
  userAddress: string;
  userRole: string;
  groupIds: string[];
}

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, RouterModule],
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css']
})
export class RegisterComponent implements OnInit {
  registerForm!: FormGroup;
  isLoading: boolean = false;
  showPassword: boolean = false;
  showConfirmPassword: boolean = false;
  errorMessage: string = '';

  constructor(
    private fb: FormBuilder,
    private authService: AuthService,
    private router: Router
  ) {
    this.initializeForm();
  }

  ngOnInit() {
    // Subscribe to form value changes for debugging
    this.registerForm.valueChanges.subscribe(value => {
      console.log('Form values:', value);
      console.log('Form valid:', this.registerForm.valid);
      console.log('Form errors:', this.registerForm.errors);
    });
  }

  private initializeForm() {
    this.registerForm = this.fb.group({
      userName: ['', [
        Validators.required,
        Validators.minLength(2),
        Validators.maxLength(50)
      ]],
      userEmail: ['', [
        Validators.required,
        Validators.email,
        Validators.pattern('^[a-z0-9._%+-]+@[a-z0-9.-]+\\.[a-z]{2,4}$')
      ]],
      userMobileNum: ['', [
        Validators.required,
        Validators.pattern('^[0-9]{10}$')
      ]],
      userAddress: ['', [
        Validators.required,
        Validators.minLength(5)
      ]],
      userRole: ['', Validators.required],
      password: ['', [
        Validators.required,
        Validators.minLength(6),
        Validators.pattern('^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#$%^&*])[a-zA-Z0-9!@#$%^&*]{6,}$')
      ]],
      confirmPassword: ['', Validators.required]
    }, { validators: RegisterComponent.passwordMatchValidator });
  }

  // Updated to static method
  static passwordMatchValidator(g: FormGroup) {
    const password = g.get('password')?.value;
    const confirmPassword = g.get('confirmPassword')?.value;
    return password === confirmPassword ? null : { 'passwordMismatch': true };
  }

  // Getters for form controls - useful in template
  get f() {
    return this.registerForm.controls;
  }

  // Toggle password visibility
  togglePassword() {
    this.showPassword = !this.showPassword;
  }

  toggleConfirmPassword() {
    this.showConfirmPassword = !this.showConfirmPassword;
  }

  // Get error message for password
  getPasswordErrorMessage(): string {
    const control = this.registerForm.get('password');
    if (control?.errors) {
      if (control.errors['required']) {
        return 'Password is required';
      }
      if (control.errors['minlength']) {
        return 'Password must be at least 6 characters';
      }
      if (control.errors['pattern']) {
        return 'Password must contain at least one uppercase letter, one lowercase letter, one number and one special character';
      }
    }
    return '';
  }

  // Form submission
  onSubmit() {
    console.log('Submit button clicked');
    console.log('Form value:', this.registerForm.value);
    console.log('Form valid:', this.registerForm.valid);

    if (this.registerForm.valid) {
      this.isLoading = true;
      this.errorMessage = '';

      // Create user object without userId (will be generated by backend)
      const user: User = {
        userName: this.registerForm.value.userName,
        userEmail: this.registerForm.value.userEmail,
        password: this.registerForm.value.password,
        userMobileNum: this.registerForm.value.userMobileNum,
        userAddress: this.registerForm.value.userAddress,
        userRole: this.registerForm.value.userRole,
        groupIds: [] // Initialize with empty array
      };

      console.log('Sending registration request with user:', user);

      this.authService.register(user).subscribe({
        next: (response) => {
          console.log('Registration successful:', response);
          // Show success message
          this.showSuccessMessage('Registration successful! Redirecting to login...');
          // Redirect to login after a short delay
          setTimeout(() => {
            this.router.navigate(['/login']);
          }, 2000);
        },
        error: (error) => {
          console.error('Registration failed:', error);
          this.errorMessage = error.error?.message || 'Registration failed. Please try again.';
          this.isLoading = false;
        },
        complete: () => {
          this.isLoading = false;
        }
      });
    } else {
      this.handleInvalidForm();
    }
  }

  private showSuccessMessage(message: string) {
    // You can implement this using a toast notification service
    // For now, we'll just set it to errorMessage (you might want to create a separate success message property)
    this.errorMessage = message;
  }

  private handleInvalidForm() {
    console.log('Form is invalid');
    this.errorMessage = 'Please fix the errors in the form.';
    Object.keys(this.registerForm.controls).forEach(key => {
      const control = this.registerForm.get(key);
      if (control?.errors) {
        console.log(`Errors in ${key}:`, control.errors);
      }
      control?.markAsTouched();
    });
  }
  // Reset form
  resetForm() {
    this.registerForm.reset();
    this.errorMessage = '';
  }

  // Helper method to check if field is invalid
  isFieldInvalid(fieldName: string): boolean {
    const field = this.registerForm.get(fieldName);
    return field ? (field.invalid && (field.dirty || field.touched)) : false;
  }

  // Helper method to get error message for a field
  getErrorMessage(fieldName: string): string {
    const control = this.registerForm.get(fieldName);
    if (control?.errors) {
      if (control.errors['required']) {
        return `${fieldName.charAt(0).toUpperCase() + fieldName.slice(1)} is required`;
      }
      if (control.errors['email']) {
        return 'Please enter a valid email address';
      }
      if (control.errors['pattern']) {
        switch (fieldName) {
          case 'userMobileNum':
            return 'Please enter a valid 10-digit mobile number';
          case 'userEmail':
            return 'Please enter a valid email address';
          default:
            return 'Invalid format';
        }
      }
      if (control.errors['minlength']) {
        return `${fieldName.charAt(0).toUpperCase() + fieldName.slice(1)} must be at least ${control.errors['minlength'].requiredLength} characters`;
      }
    }
    return '';
  }
}